export enum SyncTarget {
  TEAMS = 'TEAMS',
  MATCHES = 'MATCHES',
  PLAYER_ENRICHMENT = 'PLAYER_ENRICHMENT',
  PLAYER_MATCH_STATISTICS = 'PLAYER_MATCH_STATISTICS',
  SEASON_STATISTICS = 'SEASON_STATISTICS',
  FULL = 'FULL',
}
